language: minimal
dist: trusty

branches:
  only:
    - master

services:
  - docker

script:
  - docker build --rm -t toxsickcoder/node-typescript-starter:latest .
  - docker run --rm -it toxsickcoder/node-typescript-starter:latest
